# Name of the github-docker workflow
name: Grid

# Perform tests on pull request
on:
  workflow_dispatch:

  pull_request:
    branches: 
      - main
      - staged
      - development
    paths-ignore:
      - '**.md'
      - 'sites/**'
      - 'docs/**'
      - 'LICENSE'
    
# Container jobs
jobs:
  Grid:
    name: "Grid"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akashdhruv/Maple/.github/actions/maple@main
      with:
        singularity-version: 3.8.3
    - name: Run tests
      run: |   
          python3 tests/Grid/Grid.py
