# Name of the github-docker workflow
name: incompFlow

# Perform tests on pull request
on:
  workflow_dispatch:

  pull_request:
    branches: 
      - main
      - staged
      - development
    paths-ignore:
      - '**.md'
      - 'sites/**'
      - 'docs/**'
      - 'LICENSE'
    
# Container jobs
jobs:

  # 1
  PoolBoiling:
    name: "PoolBoiling"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2      
    - name: Dependencies1
      run: |
          mkdir -p $HOME/.local/bin
          export PATH="PATH:$HOME/.local/bin"
    - uses: actions/checkout@v2 # checkout root
    - name: Checkout submodules # checkout rest
      run: |
          # If your submodules are configured to use SSH instead of HTTPS 
          # please uncomment the following line
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule update --init tools/maple
          cd tools/maple
          ./setup develop
          ./setup clean
    - name: Run Maple API
      run: |   
          python3 container/incompFlow/PoolBoiling.py

  # 2
  RisingBubble:
    name: "RisingBubble"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2      
    - name: Dependencies1
      run: |
          mkdir -p $HOME/.local/bin
          export PATH="PATH:$HOME/.local/bin"
    - uses: actions/checkout@v2 # checkout root
    - name: Checkout submodules # checkout rest
      run: |
          # If your submodules are configured to use SSH instead of HTTPS 
          # please uncomment the following line
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule update --init tools/maple
          cd tools/maple
          ./setup develop
          ./setup clean
    - uses: eWaterCycle/setup-singularity@v7
    - name: Run tests
      run: |   
          python3 container/incompFlow/RisingBubble.py
