# Name of the github-docker workflow
name: incompFlow

# Perform tests on pull request
on:
  workflow_dispatch:

  pull_request:
    branches: 
      - main
      - staged
      - development
    paths-ignore:
      - '**.md'
      - 'sites/**'
      - 'docs/**'
      - 'LICENSE'
    
# Container jobs
jobs:

  # 1
  PoolBoiling:
    name: "PoolBoiling"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akashdhruv/Maple/.github/actions/maple@main
    - name: Run Maple API
      run: |   
          python3 tests/incompFlow/PoolBoiling.py

  # 2
  RisingBubble:
    name: "RisingBubble"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akashdhruv/Maple/.github/actions/maple@main
    - uses: eWaterCycle/setup-singularity@v7
      with:
        singularity-version: 3.8.3
    - name: Run tests
      run: |   
          python3 tests/incompFlow/RisingBubble.py

  # 3
  LidDrivenCavity:
    name: "LidDrivenCavity"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akashdhruv/Maple/.github/actions/maple@main
    - uses: eWaterCycle/setup-singularity@v7
      with:
        singularity-version: 3.8.3
    - name: Run tests
      run: |   
          python3 tests/incompFlow/LidDrivenCavity
