name: ubuntu-serial

on:
  workflow_dispatch:

  #pull_request:
  #  branches: 
  #    - master
  #    - staged
  #    - development
  #  paths-ignore:
  #    - '**.md'
  #    - 'sites/**'
  #    - 'docs/**'
  #    - 'LICENSE'

  #push:
  #  branches: 
  #    - master
  #    - staged
  #    - development
  #  paths-ignore:
  #    - '**.md'
  #    - 'sites/**'
  #    - 'docs/**'
  #    - 'LICENSE'
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ubuntu-latest:
    name: "sod-sedov"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2      
    - name: Dependencies1
      run: |
          mydir="$PWD"
          sudo apt-get update
          sudo apt-get install libhdf5-mpi-dev  
    - name: Flash setup
      run: |   
          mydir="$PWD"
          echo $mydir
          cd $mydir/sites/hello
          mv Makefile.h Makefile.h.hello
          wget https://gist.githubusercontent.com/rajeeja/768b83c41c64563e81df84d4021b9bd4/raw/a883c1e6c6cb5ded3aaa895c104fbb1d0ae67fbd/Makefile.h
          cd ../..
          ./setup Sod -auto -debug -site=hello -objdir=sod-serial
          ./setup Sedov -auto -debug -site=hello -objdir=sedov-serial
    - name: Flash serial make
      run: |
          mydir="$PWD"
          echo $mydir
          cd sod-serial
          make 
          echo "DONE: Sod serial make"          
          cd ../sedov-serial/
          make           
          echo "DONE: Sod serial make"          
    - name: Flash serial run
      run: |          
          mydir="$PWD"
          echo $mydir
          cd sod-serial   
          echo "RUNNING: Sod serial"
          ./flash5     
          ls -ltrh *chk*
          head -n 21 *.log
          tail -n 200 *.log
          cd ../sedov-serial
          echo "RUNNING: Sedov serial"
          ./flash5     
          ls -ltrh *chk*
          head -n 21 *.log
          tail -n 200 *.log          

